shopify/inventory/urls.py
from django.urls import path
from .views import Inventories, create, ViewInventory_Items, create_item
from .views import update_item, delete_item, view_deleteditems, undo_deletion

app_name = 'inventory'

urlpatterns =[
    path('', Inventories.as_view(), name='inventories'),
    path('add/', create, name='add_inventory'),
    path('view/<int:inventory_id>/', ViewInventory_Items, name='view_inventory'),
    path('add/item/<int:inventory_id>', create_item, name='create_item'),
    path('edit/item/<int:item_id>', update_item, name='edit_item'),
    path('delete/item/<int:item_id>', delete_item, name='delete_item'),
    path('view/deleteditems/<int:inventory_id>/', view_deleteditems, name='deleted_items'),
    path('undo_deletion/<int:item_id>', undo_deletion, name='undo_deletion')

]

shopify/shopify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls'))
]

shopify/inventory/models.py
from django.db import models

class Inventory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'Name:{self.name}'

class Item(models.Model):
    name = models.TextField(max_length=50)
    price = models.IntegerField()
    sales = models.IntegerField()
    in_stock = models.BooleanField(default=False)
    quantity = models.IntegerField()
    deletion_comment = models.CharField(max_length=100)
    deleted = models.BooleanField(default=False)
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)


    def __str__(self):
        return f'Name: {self.name}, Price:{self.price}, Quantity:{self.quantity}'

shopify/inventory/views.py
from django.shortcuts import render
from .models import Inventory, Item
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect

def create(request):
    """ create a new inventory product """
    if request.method == 'POST':
        inventory_name = request.POST['name']
        inventory = Inventory.objects.filter(name=inventory_name).first()
        if inventory is None:
            Inventory.objects.create(name=inventory_name)
            return HttpResponseRedirect(reverse('inventory:inventories'))
        else:
            error = 'Inventory name exist!, Please input a new inventory'
            return render(request, 'inventory/add_inventory.html', {'error_message': error})

    else:
        return render(request, 'inventory/add_inventory.html')

class Inventories(generic.ListView):
    """ returns a list of inventory items """
    model = Inventory
    template_name = 'inventory/home.html'
    context_object_name = 'inventories'

    def get_queryset(self):
        return Inventory.objects.all()





def ViewInventory_Items(request, inventory_id):
    try:
        inventory = Inventory.objects.get(pk=inventory_id)
    except(KeyError, Inventory.DoesNotExist):
        error_message = 'Inventory does not exist'
        inventories = Inventory.objects.all()
        context = {'error': error_message, 'inventories': inventories}
        return render(request, 'inventory/home.html', context)
    else:
        inventory_items = inventory.item_set.filter(deleted=False).all()
        context = {'inventory': inventory, 'inventory_items': inventory_items}
        return render(request, 'inventory/veiw_inventory.html', context)


def create_item(request, inventory_id):
    """ create a new inventory product """
    try:
        inventory = Inventory.objects.get(pk=inventory_id)
    except(KeyError, Inventory.DoesNotExist):
        error_message = 'Inventory does not exist'
        inventories = Inventory.objects.all()
        context = {'error': error_message, 'inventories': inventories}
        return render(request, 'inventory/home.html', context)
    if request.method == 'POST':
        # check if item is in database
        item = Item.objects.filter(name=request.POST['name']).first()
        if item is None:
            add = request.POST
            Item.objects.create(name=add['name'], quantity=add['quantity'],
                            sales=add['sales'], price=add['price'], inventory_id=inventory.id,
                            in_stock=add.get('in_stock', False))
            return HttpResponseRedirect(reverse('inventory:view_inventory', args=(inventory.id,)))
        else:  # item exists
            error_message = 'Cannot add item with duplicate Name!'
            context = {'error': error_message, 'inventory': inventory}
            return render(request, 'inventory/add_item.html', context)
    else:
        return render(request, 'inventory/add_item.html', {'inventory': inventory})


def delete_item(request, item_id):
    try:
        item = Item.objects.get(pk=item_id)
    except(KeyError, Item.DoesNotExist):
        error_message = 'Item does not exist'
        inventories = Inventory.objects.all()
        context = {'error': error_message, 'inventories': inventories}
        return render(request, 'inventory/home.html', context)
    inventory = Inventory.objects.get(pk=item.inventory_id)
    if request.method == 'POST':
        item.deleted = True
        item.deletion_comment = request.POST['comment']
        item.save()
        return HttpResponseRedirect(reverse('inventory:view_inventory', args=(inventory.id,)))
    else:
        return render(request, 'inventory/delete_item.html', {'item': item, 'inventory_name': inventory.name})


def update_item(request, item_id):
    try:
        item = Item.objects.get(pk=item_id)
    except(KeyError, Item.DoesNotExist):
        error_message = 'Item does not exist'
        inventories = Inventory.objects.all()
        context = {'error': error_message, 'inventories': inventories}
        return render(request, 'inventory/home.html', context)
    if request.method == 'POST':
        add = request.POST
        check_item = Item.objects.filter(name=request.POST['name']).first()
        if check_item is None or item.name==add['name']:
            item.name = add['name']
            item.quantity = add['quantity']
            item.sales = add['sales']
            item.in_stock = add.get('in_stock', False)
            item.price = add['price']
            item.save()
            return HttpResponseRedirect(reverse('inventory:view_inventory', args=(item.inventory_id,)))
        else:
            error_message = 'Cannot add item with duplicate Name!'
            context = {'error': error_message, 'item': item}
            return render(request, 'inventory/edit_item.html', context)
    else:
        return render(request, 'inventory/edit_item.html', {'item': item})


def view_deleteditems(request, inventory_id):
    try:
        inventory = Inventory.objects.get(pk=inventory_id)
    except(KeyError, Inventory.DoesNotExist):
        error_message = 'Inventory does not exist'
        inventories = Inventory.objects.all()
        context = {'error': error_message, 'inventories': inventories}
        return render(request, 'inventory/home.html', context)
    else:
        inventory_items = inventory.item_set.filter(deleted=True).all()
        context = {'inventory': inventory, 'inventory_items': inventory_items}
        return render(request, 'inventory/deleted_items.html', context)



def undo_deletion(request, item_id):
    try:
        item = Item.objects.get(pk=item_id)
    except(KeyError, Item.DoesNotExist):
        error_message = 'Item does not exist'
        inventories = Inventory.objects.all()
        context = {'error': error_message, 'inventories': inventories}
        return render(request, 'inventory/home.html', context)
    else:
        inventory = Inventory.objects.get(pk=item.inventory_id)
        item.deleted = False
        item.save()
        return HttpResponseRedirect(reverse('inventory:view_inventory', args=(inventory.id,)))

shopify/inventory/templates/inventory/add_inventory.html
{% extends 'inventory/base.html' %}

{% block content %}
   <div>
      <h3>Shopify Inventory Management Application - All Inventories</h3>
      <p>Create an inventory and keep track of items</p>
   </div>
<form action="{% url 'inventory:add_inventory' %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="addinventory">Inventory Name</label> <span style="color:red">{{ error_message }}</span>
    <input type="text" class="form-control" id="addinventory" placeholder="new inventory" name="name" required>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

shopify/inventory/templates/inventory/add_item.html
{% extends 'inventory/base.html' %}

{% block content %}
 <h3>Shopify Inventory Management Application -- {{ inventory.name }}</h3>
<form action="{% url 'inventory:create_item' inventory.id %}" method="POST">
    {% csrf_token %}
    {% if error %}
    <span class="btn btn-danger">{{ error }}</span><br><br>
    {% endif %}
    <div class="form-group ">
        <label for="name">Name</label>
        <input type="text" id="name" placeholder="Item Name" name="name" required >
    </div>
    <div class="form-group ">
        <label for="quantity">Quantity</label>
        <input type="number" id="quantity" placeholder="Quantity in stock" name="quantity" required>
    </div>
    <div class="form-group ">
        <label for="price">Price</label>
        <input type="text" id="price" placeholder="Item Price" name="price" required>
    </div>
    <div class="form-group ">
        <label for="sales">Sales</label>
        <input type="number" id="sales" placeholder="Number of items sold" name="sales" required>
    </div>
    <div class="form-group">
        <label for="stock">In Stock</label>
        <input type="checkbox" id="stock" name="in_stock" value="True">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

shopify/inventory/templates/inventory/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <title>Shopify Inventory</title>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css"
         integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
   <div class="d-flex justify-content-center align-items-center container" style="margin-top: 10%">
      {% block content %}
      {% endblock %}
   </div>
</body>
</html>

shopify/inventory/templates/inventory/delete_item.html
{% extends 'inventory/base.html' %}

{% block content %}
   <h2>Delete {{ item.name }} from {{ inventory_name }} inventory</h2>

   <input class="form-control" value="{{ item.name }}" disabled>
   <input class="form-control" value="{{ item.quantity }}" disabled>
   <input class="form-control" value="{{ item.price }}" disabled>
   <input class="form-control" value="{{ item.sales }}" disabled><br>

   <form method="POST" action=#>
     {% csrf_token %}

      <div class="form-group">
         <label for="comment">Comment</label>
         <input type="text" id="comment" name="comment" required placeholder="Enter deletion comment">
      </div>
      <input class="btn btn-primary"   type="submit" value="Delete">
   </form>
{% endblock %}

shopify/inventory/templates/inventory/deleted_items.html
{% extends 'inventory/base.html' %}

{% block content %}
   <div>
      <h3>Shopify Inventory Management Application - Items Deleted from {{ inventory.name }}</h3>
      <div>
       <table class="table">
          <thead>
            <tr>
               <th scope="col">Name</th>
               <th scope="col">Price</th>
               <th scope="col">Quantity</th>
               <th scope="col">In stock</th>
               <th scope="col">Sales</th>
                <th scope="col">Comment</th>
            </tr>
          </thead>
          <tbody>
            {% for item in inventory_items %}
               <tr>
                  <td>{{ item.name }}</td>
                  <td>{{ item.price }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.in_stock }}</td>
                  <td>{{ item.sales }}</td>
                   <td>{{ item.deletion_comment }}</td>

                  <td>
                     <a class="btn btn-primary" href="{% url 'inventory:undo_deletion' item.id%}">
                        Undo Deletion</a>
                  </td>
               </tr>
            {% endfor %}
          </tbody>
       </table>
    </div>
   </div>
{% endblock %}

shopify/inventory/templates/inventory/edit_item.html
{% extends 'inventory/base.html' %}

{% block content %}
 <h3>Shopify Inventory Management Application -- {{ item.name }}</h3>
<form action="{% url 'inventory:edit_item' item.id %}" method="POST">
    {% csrf_token %}
    {% if error %}
    <span class="btn btn-danger">{{ error }}</span><br><br>
    {% endif %}
    <div class="form-group ">
        <label for="name">Name</label>
        <input type="text" id="name" placeholder="Item Name" name="name" value="{{ item.name}}"required >
    </div>
    <div class="form-group ">
        <label for="quantity">Quantity</label>
        <input type="number" id="quantity" placeholder="Quantity in stock" name="quantity" value="{{ item.quantity }}" required>
    </div>
    <div class="form-group ">
        <label for="price">Price</label>
        <input type="text" id="price" placeholder="Item Price" name="price" value="{{ item.price}}" required>
    </div>
    <div class="form-group ">
        <label for="sales">Sales</label>
        <input type="number" id="sales" placeholder="Number of items sold" name="sales" value="{{ item.sales }}" required>
    </div>
    <div class="form-group">
        <label for="stock">In Stock</label>
        <input type="checkbox" id="stock" name="in_stock" value="True">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

shopify/inventory/templates/inventory/home.html
{% extends 'inventory/base.html' %}
{% block content %}
<div>
      <h3>Shopify Inventory Management Application - All Inventories</h3>
      <p>Create an inventory and keep track of items</p>
   </div>
    {% if error %}
    <span class="btn btn-danger">{{ error }}</span><br><br>
    {% endif %}
    <div>
       {% if inventories %}
          <table class="table">
             <thead>
               <tr>
                  <th scope="col">Name</th>
                  <th scope="col">#</th>
               </tr>
             </thead>
             <tbody>
               {% for inventory in inventories %}
                  <tr>
                     <td>{{ inventory.name }}</td>
                     <th scope="row">
                        <a class="btn btn-primary" href="{% url 'inventory:view_inventory' inventory.id%}">View</a>
                     </th>
                  </tr>
               {% endfor %}
             </tbody>
          </table>
         {% else %}
            <p>No inventory available.</p>
       {% endif %}
       <div>
         <a class="btn btn-primary" href="{% url 'inventory:add_inventory' %}">Add Inventory</a>
       </div>
    </div>
{% endblock %}

shopify/inventory/templates/inventory/veiw_inventory.html
{% extends 'inventory/base.html' %}

{% block content %}
   <div>
      <h3>Shopify Inventory Management Application - {{ inventory.name }}</h3>
      <a class="btn btn-primary" href="{{ url_for('items.add_inventory_item', inventory_name=inventory.name) }}">Add Item</a>
      <a class="btn btn-primary" href="{{ url_for('inventory.deleted_inventory_items', inventory_name=inventory.name) }}">Deleted items</a>
   </div>

    <div>
       <table class="table">
          <thead>
            <tr>
               <th scope="col">Name</th>
               <th scope="col">Price</th>
               <th scope="col">Quantity</th>
               <th scope="col">In stock</th>
               <th scope="col">Sales</th>
            </tr>
          </thead>
          <tbody>
            {% for item in inventory.items_set.all %}
               <tr>
                  <td>{{ item.name }}</td>
                  <td>{{ item.price }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.in_stock }}</td>
                  <td>{{ item.sales }}</td>
                  <td>
                     <a class="btn btn-primary" href=#>
                        Edit</a>
                  </td>
                  <td>
                     <a class="btn btn-danger" href=#>
                        Delete</a>
                  </td>
               </tr>
            {% endfor %}
          </tbody>
       </table>
    </div>
{% endblock %}

shopify/items/templates/items/inventory_list.html
{% extends 'items/base.html' %}

{% block content %}
   <div>
      <h3>Shopify Inventory Management Application - {{ inventory.name }}</h3>
      <a class="btn btn-primary" href="{{ url_for('items.add_inventory_item', inventory_name=inventory.name) }}">Add Item</a>
      <a class="btn btn-primary" href="{{ url_for('inventory.deleted_inventory_items', inventory_name=inventory.name) }}">Deleted items</a>
   </div>

    <div>
       <table class="table">
          <thead>
            <tr>
               <th scope="col">Name</th>
               <th scope="col">Price</th>
               <th scope="col">Quantity</th>
               <th scope="col">In stock</th>
               <th scope="col">Sales</th>
            </tr>
          </thead>
          <tbody>
            {% for item in inventory.items %}
               <tr>
                  <td>{{ item.name }}</td>
                  <td>{{ item.price }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.in_stock }}</td>
                  <td>{{ item.sales }}</td>
                  <td>
                     <a class="btn btn-primary" href="{{ url_for('items.edit_inventory_item', inventory_name=inventory.name, item_id=item._id) }}">
                        Edit</a>
                  </td>
                  <td>
                     <a class="btn btn-danger" href="{{ url_for('items.delete_inventory_item', inventory_name=inventory.name, item_id=item._id) }}">
                        Delete</a>
                  </td>
               </tr>
            {% endfor %}
          </tbody>
       </table>
    </div>
{% endblock %}